### ISSUE TITLE
update libfreenect2

### ISSUE THREAD

**Issue by lucbettaieb** [cwru-robotics/external_packages#1]
messes up when cmake-ing

**Comment by wsnewman** [comment]
Ah.  Shucks.  Can you fix it?  (or just change the package.xml to
package.xml.nocompile?)

On Tue, Sep 1, 2015 at 12:35 PM, Luc Bettaieb notifications@github.com
wrote:

> messes up when cmake-ing
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cwru-robotics/external_packages/issues/1.

## 

Wyatt Newman, Ph.D., P.E.
Professor, EECS Dept
Case Western Reserve University
Cleveland, OH 44106
216-368-6432
wyatt.newman@case.edu

**Comment by lucbettaieb** [comment]
Yep, just a note to myself
